In [1]:
import numpy as np
np.__version__

'1.20.3'

# 1. 배열 생성


### 리스트로 배열 만들기
- 1D array, 2D array, 3D array

In [2]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [3]:
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 1], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [4]:
a3 = np.array([ [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
                [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
                [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ] ])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

 - zeros() : 모든 요소를 0으로 초기화

In [5]:
np.zeros(10) # 10개의 요소를 0으로 초기화된 배열을 만들어줘.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- ones() : 모든 요소를 1로 초기화

In [6]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- full() : 모든 요소를 지정한 값으로 초기화

In [7]:
np.full((3, 3), 1.23) # 3 by 3 짜라의 1.23으로 값이 채워진 배열 생성

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

- eye() : 단위행렬(identity matrix) 생성
> 주대각선의 원소가 모두 1이고 원소는 모두 0인 정사각 행렬

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- tri() : 삼각행렬 생성

In [9]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

- empty() : 초기화되지 않은 배열 생성
> 초기화가 없어서 배열 생성비용 저렴하고 빠름  
> 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [10]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- _like() : 지정된 배열과 shape가 같은 행렬 생성
> np.zeros_like()  
> np.ones_like()  
> np.full_like()  
> np.empty_like()

In [11]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [12]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

- arange() : 정수 범위로 배열 생성

In [14]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

- linspace() : 범위 내에서 균등 간격의 배열 생성

In [15]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- logspace() : 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [16]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성

- random.random() : 랜덤한 수의 배열 생성

In [17]:
np.random.random((3, 3))

array([[0.81129377, 0.03405418, 0.88614453],
       [0.51630369, 0.5334839 , 0.52999543],
       [0.47571319, 0.22337318, 0.28702391]])

- random.randint() : 일정 구간의 랜덤 정수의 배열 생성

In [18]:
np.random.randint(0, 10, (3, 3))

array([[8, 6, 4],
       [8, 8, 8],
       [4, 8, 1]])

- random.normal() : 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성  
- 평균 = 0, 표준편차 = 1, 3 x 3 배열

In [19]:
np.random.normal(0, 1, (3, 3))

array([[-0.18042632, -2.33849369, -0.88501532],
       [ 0.12751127,  1.82127901, -0.73540408],
       [ 0.10545183,  0.46561266, -0.93002282]])

- random.rand() : 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [20]:
np.random.rand(3, 3)

array([[0.34954842, 0.40544369, 0.42805656],
       [0.0205975 , 0.22780659, 0.39759453],
       [0.62957502, 0.50197902, 0.88926633]])

- random.randn() : 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [21]:
np.random.randn(3, 3)

array([[-1.48171888, -0.79277209, -0.27645656],
       [ 0.52460364,  0.76189318,  1.65537514],
       [ 1.17973461,  0.1423144 , -0.04081415]])

### 표준 데이터 타입

In [22]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [24]:
np.full((3, 3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성

In [25]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [26]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [27]:
datetime = np.datetime64('2020-01-01 12:00')
datetime

numpy.datetime64('2020-01-01T12:00')

In [28]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

# 2. 배열 조회

## 배열 속성 정보

In [29]:
def array_info(array):
    print(array)
    print('ndim :', array.ndim) # 디멘젼이 몇인지 나타내줌
    print('shape : ', array.shape)
    print('dtype : ', array.dtype)
    print('size : ', array.size)
    print('itemsize : ', array.itemsize)
    print('nbytes : ', array.nbytes)
    print('strides : ', array.strides)

In [30]:
array_info(a1)

[4 5 6 4 5]
ndim : 1
shape :  (5,)
dtype :  int32
size :  5
itemsize :  4
nbytes :  20
strides :  (4,)


In [31]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim : 2
shape :  (3, 3)
dtype :  int32
size :  9
itemsize :  4
nbytes :  36
strides :  (12, 4)


In [32]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim : 3
shape :  (3, 3, 3)
dtype :  int32
size :  27
itemsize :  4
nbytes :  108
strides :  (36, 12, 4)


## 인덱싱(Indexing)

In [33]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [34]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, 1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [35]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[2, 2, 2])
print(a3[2, -1, -1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


## 슬라이싱(Slicing)

- 슬라이싱 구문 : a[start:stop:step]  
- 기본값 : start = 0, stop = ndim, step = 1

In [36]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [37]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


## 불리언 인덱싱(Boolean Indexing)
- 배열 각 요소의 선택 여부를 불리언(True or False)로 지정  
- True 값인 인덱스의 값만 조회

In [38]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [39]:
print(a2)
bi = np.random.randint(0, 2, (3, 3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True False]
 [ True False False]
 [ True  True False]]
[1 2 4 7 8]


## 펜시 인덱싱(Fancy Indexing)

In [40]:
print(a1)
print([a1[0], a1[2]])
ind = [0, 2]
print(a1[ind])
ind = np.array([[0, 1],
               [2, 0]])
print(a1[ind])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [41]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


## 3. 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입
- insert(): 배열의 특정 위치에 값 삽입  
- axis를 지정하지 않으면 1차원 배열로 변환  
- 추가할 방향을 axis로 지정  
- 원본 배열 변경없이 새로운 배열 반환

In [42]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[ 4  5 10  6  4  5]


In [43]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정
- 배열의 인덱싱으로 접근하여 값 수정

In [44]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4]) # 팬시 인덱싱
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[4 5 6 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [45]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1
print(a2)
a2[1:, 2] = 9
print(a2)
row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 0 # 팬시 인덱싱
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제
- delete() : 배열의 특정 위치에 값 삭제  
- axis를 지정하지 않으면 1차원 배열로 전환  
- 삭제할 방향을 axis로 지정  
- 원본 배열 변경없이 새로운 배열 반환

In [46]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [47]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


### 배열 복사
 - 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [48]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2] # copy() 를 안쓰면 원본까지 바뀜
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)
print(a2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


- copy() : 배열이나 하위 배열 내의 값을 명시적으로 복사

In [49]:
print(a2)
a2_sub_copy = a2[:2, :2].copy() # copy() 를 써서 원본 안바뀜
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


## 4. 배열 변환

### 배열 전치 및 축 변경

In [50]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [51]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [52]:
print(a2)
print(a2.swapaxes(1, 0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [53]:
print(a3)
print(a3.swapaxes(0, 1))
print(a3.swapaxes(1, 2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화

- reshape() : 배열의 형상을 변경

In [54]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- newaxis() : 새로운 축 추가

In [55]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

- 배열 모양만 변경

In [56]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5, 2))
print(n2)

[[9 8 7 8 8]
 [1 5 9 0 4]]
[[9 8]
 [7 8]
 [8 1]
 [5 9]
 [0 4]]


- 배열 크기 증가  
- 남은 공간은 0으로 채워짐

In [57]:
n2.resize((5, 5))
print(n2)

[[9 8 7 8 8]
 [1 5 9 0 4]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


- 배열 크기 감소  
- 포함되지 않은 값은 삭제됨

In [58]:
n2.resize((3, 3))
print(n2)

[[9 8 7]
 [8 8 1]
 [5 9 0]]


### 배열 추가

- append() : 배열의 끝에 값 추가

In [59]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


- axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [60]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


- axis를 0으로 지정  
- shape[0]을 제외한 나머지 shape은 같아야 함

In [61]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


- axis를 1로 지정  
- shape[1]을 제외한 나머지 shape은 같아야 함

In [62]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

- concatenate() : 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [63]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [64]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [67]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [68]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- vstack() : 수직 스택(vertical stack), 1차원으로 연결

In [69]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- hstack() : 수평 스택(horizontal stack), 2차원으로 연결

In [70]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- dstack() : 깊이 스택(depth stack), 3차원으로 연결

In [71]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

- stack() : 새로운 차원으로 연결

In [72]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

- split() : 배열 분할

In [75]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


- vsplit() : 수직 분할, 1차원으로 분할

In [77]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


- hsplit() : 수평 분할, 2차원으로 분할

In [78]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


- dsplit() : 깊이 분할, 3차원으로 분할

In [80]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


## 5. 배열 연산

- NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용  
- 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현  
- 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [83]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(a1+ a2)

b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)
print(a1 + b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [97]:
a1 = np.arange(1, 10)
print(a1)
print(a1 + 1)
print(np.add(a1, 10))
print(a1 - 2)
print(np.subtract(a1, 10))
print(-a1)
print(np.negative(a1))
print(a1 * 2)
print(np.multiply(a1, 2))
print(a1 / 2)
print(np.divide(a1, 2))
print(a1 // 2)
print(np.floor_divide(a1, 2)) # floor_ 는 '내림'
print(a1 ** 2)
print(np.power(a1, 2)) # a1[idx] * a1[idx]
print(a1 % 2)
print(np.mod(a1, 2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [99]:
a1 = np.arange(1, 10)
print(a1)
b1 = np.random.randint(1, 10, size=9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[1 8 6 9 3 1 7 1 9]
[ 2 10  9 13  8  7 14  9 18]
[ 0 -6 -3 -5  2  5  0  7  0]
[ 1 16 18 36 15  6 49  8 81]
[1.         0.25       0.5        0.44444444 1.66666667 6.
 1.         8.         1.        ]
[1 0 0 0 1 6 1 8 1]
[        1       256       729    262144       125         6    823543
         8 387420489]
[0 2 3 4 2 0 0 0 0]


In [101]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.random.randint(1, 10, size=(3, 3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 1]
 [3 6 3]
 [3 6 5]]
[[ 5  7  4]
 [ 7 11  9]
 [10 14 14]]
[[-3 -3  2]
 [ 1 -1  3]
 [ 4  2  4]]
[[ 4 10  3]
 [12 30 18]
 [21 48 45]]
[[0.25       0.4        3.        ]
 [1.33333333 0.83333333 2.        ]
 [2.33333333 1.33333333 1.8       ]]
[[0 0 3]
 [1 0 2]
 [2 1 1]]
[[     1     32      3]
 [    64  15625    216]
 [   343 262144  59049]]
[[1 2 0]
 [1 5 0]
 [1 2 4]]


절대값 함수(Absolute Function)
- absolute(), abs() : 내장된 절대값 함수

In [106]:
a1 = np.random.randint(-10, 10, size = 5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[-7 -5  4 -3  6]
[7 5 4 3 6]
[7 5 4 3 6]


제곱/제곱근 함수
- square, sqrt : 제곱, 제곱근 함수

In [107]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[-7 -5  4 -3  6]
[49 25 16  9 36]
[       nan        nan 2.                nan 2.44948974]


C:\Users\MKK\AppData\Local\Temp/ipykernel_4988/2033102379.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


지수와 로그 함수 (Exponential and Log Function)

In [110]:
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1)) # exp -> e의 거듭제곱
print(np.exp2(a1)) # exp2 -> 2의 거듭제곱
print(np.power(a1, 2))

[7 9 4 4 4]
[1096.63315843 8103.08392758   54.59815003   54.59815003   54.59815003]
[128. 512.  16.  16.  16.]
[49 81 16 16 16]


In [111]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[7 9 4 4 4]
[1.94591015 2.19722458 1.38629436 1.38629436 1.38629436]
[2.80735492 3.169925   2.         2.         2.        ]
[0.84509804 0.95424251 0.60205999 0.60205999 0.60205999]


삼각 함수(Trigonometical Function)

In [113]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [114]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

sum() : 합 계산

In [115]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
27 27
[10  9  8] [10  9  8]
[ 8  8 11] [ 8  8 11]


cumsum() : 누적합 계산

In [118]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
[ 4  5  8 11 13 16 19 25 27]
[[ 4  1  3]
 [ 7  3  6]
 [10  9  8]]
[[ 4  5  8]
 [ 3  5  8]
 [ 3  9 11]]


diff() : 차분 계산

In [119]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
[[-3  2]
 [-1  1]
 [ 3 -4]]
[[-1  1  0]
 [ 0  4 -1]]
[[-3  2]
 [-1  1]
 [ 3 -4]]


prod() : 곱 계산

In [120]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
7776
[36 12 18]
[12 18 36]


cumprod() : 누적곱 계산

In [121]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
[   4    4   12   36   72  216  648 3888 7776]
[[ 4  1  3]
 [12  2  9]
 [36 12 18]]
[[ 4  4 12]
 [ 3  6 18]
 [ 3 18 36]]


dot() / matmul() : 점곱/행렬곱 계산

In [122]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 8  8  8]
 [ 8  8  8]
 [11 11 11]]
[[ 8  8  8]
 [ 8  8  8]
 [11 11 11]]


tensordot() : 텐서곱 계산

In [124]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
27
[[[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]]
[[ 8  8  8]
 [ 8  8  8]
 [11 11 11]]


cross() : 벡터곱

In [125]:
x = [1, 2, 3]
y = [4, 5, 6]
print(np.cross(x, y))

[-3  6 -3]


inner() / outer() : 내적 / 외적

In [126]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 8  8  8]
 [ 8  8  8]
 [11 11 11]]
[[4 4 4 4 4 4 4 4 4]
 [1 1 1 1 1 1 1 1 1]
 [3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3]
 [2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3]
 [6 6 6 6 6 6 6 6 6]
 [2 2 2 2 2 2 2 2 2]]


mean() : 평균 계산

In [127]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
3.0
[3.33333333 3.         2.66666667]
[2.66666667 2.66666667 3.66666667]


std() : 표준 편차 계산

In [128]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
1.3333333333333333
[0.47140452 2.1602469  0.47140452]
[1.24721913 0.47140452 1.69967317]


var() : 분산 계산

In [129]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
1.7777777777777777
[0.22222222 4.66666667 0.22222222]
[1.55555556 0.22222222 2.88888889]


min() : 최소값

In [130]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
1
[3 1 2]
[1 2 2]


max() : 최대값

In [131]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
6
[4 6 3]
[4 3 6]


argmin() : 최소값 인덱스

In [132]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
1
[1 0 2]
[1 1 2]


argmax() : 최대값 인덱스

In [133]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
7
[0 2 0]
[0 0 1]


median() : 중앙값

In [134]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[4 1 3]
 [3 2 3]
 [3 6 2]]
3.0
[3. 2. 3.]
[3. 3. 3.]


percentile() : 백분위 수

In [135]:
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 20, 40 ,60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40 ,60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40 ,60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40 ,60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40 ,60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


any()

In [147]:
a2 = np.array([[False, False, False],
               [False, True, True],
               [False, True, True]])
print(a2)
print(np.any(a2)) # 이중 하나만 True 여도 True.
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


all()

In [150]:
a2 = np.array([[False, False, True],
               [True, True, True],
               [False, True, True]])
print(a2)
print(np.all(a2)) # 다 Ture여야 True.
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산 (Comparison Operators)

In [155]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5) # 비교 연산 후 True / Flase 결과값 리턴.
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [160]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))
print(np.any(a2 > 5))
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))
print(np.all(a2 > 5))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


In [162]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1)) # 값이 같으면 True, 다르면 False

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [168]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


불리언 연산자(Bollean Operators)

In [171]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

print((a2 > 5) & (a2 < 8)) # AND
print(a2[(a2 > 5) & (a2 < 8)]) # 불리언 인덱싱을 통해 값 출력

print((a2 > 5) | (a2 < 8)) # OR
print(a2[(a2 > 5) | (a2 < 8)]) # 불리언 인덱싱을 통해 값 출력

print((a2 > 5) ^ (a2 < 8)) # XOR
print(a2[(a2 > 5) ^ (a2 < 8)]) # 불리언 인덱싱을 통해 값 출력

print(~(a2 > 5)) # NOT
print(a2[~(a2 > 5)]) # 불리언 인덱싱을 통해 값 출력


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [174]:
a1 = np.random.randint(1, 10, size = 10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1)) # 인덱스 위치를 출력. 인덱스 값.
print(a1)
print(a1.sort())
print(a1)

[3 3 8 2 8 3 2 3 6 6]
[2 2 3 3 3 3 6 6 8 8]
[3 3 8 2 8 3 2 3 6 6]
[3 6 0 1 5 7 8 9 2 4]
[3 3 8 2 8 3 2 3 6 6]
None
[2 2 3 3 3 3 6 6 8 8]


In [176]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[7 7 4]
 [8 3 1]
 [5 6 5]]
[[5 3 1]
 [7 6 4]
 [8 7 5]]
[[4 7 7]
 [1 3 8]
 [5 5 6]]


부분 정렬  
- partition() : 배열에서 k개의 작은 값을 반환

In [178]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1, 3))

[6 5 4 6 5 9 5 6 1 4]
[1 4 4 5 5 9 5 6 6 6]


In [179]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))

[[8 7 7 6 8]
 [6 1 2 9 8]
 [4 6 3 7 2]
 [6 3 7 6 1]
 [6 9 9 5 4]]
[[6 7 7 8 8]
 [1 2 6 8 9]
 [2 3 4 6 7]
 [3 1 6 6 7]
 [5 4 6 9 9]]
[[6 3 2 6 1]
 [4 6 3 5 2]
 [6 1 7 6 4]
 [6 7 7 7 8]
 [8 9 9 9 8]]
[[6 7 7 8 8]
 [1 2 6 8 9]
 [2 3 4 6 7]
 [3 1 6 6 7]
 [5 4 6 9 9]]


## 배열 입출력

In [180]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
np.save("a", a2)

[[5 3 3 9 8]
 [5 9 9 4 8]
 [2 6 5 8 1]
 [5 5 9 8 9]
 [8 5 2 5 8]]


In [181]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 8015-6F87

 C:\Users\MKK\PythonNumPyWorkspace 디렉터리

2022-03-15  오후 05:45    <DIR>          .
2022-03-15  오후 05:45    <DIR>          ..
2022-03-08  오후 05:59    <DIR>          .ipynb_checkpoints
2022-03-08  오후 05:58             1,042 0. NumPy.ipynb
2022-03-15  오후 05:44            81,616 1. 배열 생성.ipynb
2022-03-15  오후 05:45               228 a.npy
               3개 파일              82,886 바이트
               3개 디렉터리  293,656,920,064 바이트 남음


In [183]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez("ab", a2, b2)

[[6 5 3 7 7]
 [4 6 3 8 2]
 [6 8 7 6 4]
 [6 6 9 2 9]
 [7 5 1 4 1]]


In [184]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 8015-6F87

 C:\Users\MKK\PythonNumPyWorkspace 디렉터리

2022-03-15  오후 05:47    <DIR>          .
2022-03-15  오후 05:47    <DIR>          ..
2022-03-08  오후 05:59    <DIR>          .ipynb_checkpoints
2022-03-08  오후 05:58             1,042 0. NumPy.ipynb
2022-03-15  오후 05:46            82,763 1. 배열 생성.ipynb
2022-03-15  오후 05:45               228 a.npy
2022-03-15  오후 05:47               706 ab.npz
               4개 파일              84,739 바이트
               3개 디렉터리  293,656,211,456 바이트 남음


In [185]:
npy = np.load("a.npy")
print(npy)

[[5 3 3 9 8]
 [5 9 9 4 8]
 [2 6 5 8 1]
 [5 5 9 8 9]
 [8 5 2 5 8]]


In [187]:
npz = np.load("ab.npz")
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[5 3 3 9 8]
 [5 9 9 4 8]
 [2 6 5 8 1]
 [5 5 9 8 9]
 [8 5 2 5 8]]
[[6 5 3 7 7]
 [4 6 3 8 2]
 [6 8 7 6 4]
 [6 6 9 2 9]
 [7 5 1 4 1]]


In [189]:
print(a2)
np.savetxt("a.csv", a2, delimiter=',')

[[5 3 3 9 8]
 [5 9 9 4 8]
 [2 6 5 8 1]
 [5 5 9 8 9]
 [8 5 2 5 8]]


In [190]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 8015-6F87

 C:\Users\MKK\PythonNumPyWorkspace 디렉터리

2022-03-15  오후 05:50    <DIR>          .
2022-03-15  오후 05:50    <DIR>          ..
2022-03-08  오후 05:59    <DIR>          .ipynb_checkpoints
2022-03-08  오후 05:58             1,042 0. NumPy.ipynb
2022-03-15  오후 05:50            84,788 1. 배열 생성.ipynb
2022-03-15  오후 05:50               630 a.csv
2022-03-15  오후 05:45               228 a.npy
2022-03-15  오후 05:47               706 ab.npz
               5개 파일              87,394 바이트
               3개 디렉터리  293,654,913,024 바이트 남음


In [192]:
csv = np.loadtxt("a.csv", delimiter=',') # 구분자를 ',' 로 지정
print(csv)

[[5. 3. 3. 9. 8.]
 [5. 9. 9. 4. 8.]
 [2. 6. 5. 8. 1.]
 [5. 5. 9. 8. 9.]
 [8. 5. 2. 5. 8.]]


In [194]:
print(b2)
np.savetxt("b.csv", b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5') # fmt 소수점 2자리 이하. header 정보 c1, ... 포함

[[6 5 3 7 7]
 [4 6 3 8 2]
 [6 8 7 6 4]
 [6 6 9 2 9]
 [7 5 1 4 1]]


In [195]:
csv = np.loadtxt("b.csv", delimiter=',')
print(csv)

[[6. 5. 3. 7. 7.]
 [4. 6. 3. 8. 2.]
 [6. 8. 7. 6. 4.]
 [6. 6. 9. 2. 9.]
 [7. 5. 1. 4. 1.]]
